version: '3.6'
volumes:
  postgres-volume:
    driver: local
    driver_opts:
      type: 'None'
      o: 'bind'
      device: './data'

services:

  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: polisportiva
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      network:
        ipv4_address: 10.10.0.2

  poli-nest:
    build :
      dockerfile: Dockerfile.graalvm
      context: .
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      network:
        ipv4_address: 10.10.0.3

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
