version: '3.6'
volumes:
  postgres-volume:
    driver: local
    driver_opts:
      type: 'None'
      o: 'bind'
      device: './data'

services:

  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: polisportiva
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  polisportiva-nest-js:
    image: polisportiva-nest-js:latest
#    environment:
#      DB_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
